const DHAKA_KEYWORDS = [
  "dhaka",
  "dhanmondi",
  "gulshan",
  "banani",
  "mirpur",
  "mohammadpur",
  "uttara",
  "bashundhara",
  "motijheel",
  "tejgaon",
  "shyamoli",
  "jigatola",
  "lalmatia",
  "mohakhali",
  "badda",
  "rampura",
  "khilgaon",
  "malibagh",
  "moghbazar",
  "farmgate",
  "eskaton",
  "panthapath",
  "elephant road",
  "new market",
  "hazaribagh",
  "demra",
  "sadarghat",
  "nawabganj",
  "lalbagh",
  "azimpur",
  "nilkhet",
  "shahbag",
  "ramna",
  "paltan",
  "dilkusha",
  "bijoynagar",
  "shantinagar",
  "bashabo",
  "nakhalpara",
  "karwan bazar",
  "kawran bazar",
  "old dhaka",
  "puran dhaka",
  "keraniganj",
  "narayanganj",
  "gazipur",
  "savar",
  "tongi"
];

export function isDhakaAddress(address: string): boolean {
  const normalized = address.toLowerCase();
  return DHAKA_KEYWORDS.some((kw) => normalized.includes(kw));
}
